MACRO (SETUP_APP APP_NAME)
	SET(SRC ${ARGN})
	SET(LIBS RGE ncurses)
	
	IF (WIN32)
		SET(RGE_COMPILE_FLAGS "/MD /sdl-")
		SET(CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE} ${RGE_COMPILE_FLAGS}")
		SET(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} ${RGE_COMPILE_FLAGS}")
				
		SET(CMAKE_C_FLAGS_RELWITHDEBINFO "${CMAKE_C_FLAGS_RELWITHDEBINFO} ${RGE_COMPILE_FLAGS} /Zi")
		SET(CMAKE_CXX_FLAGS_RELWITHDEBINFO "${CMAKE_CXX_FLAGS_RELWITHDEBINFO} ${RGE_COMPILE_FLAGS} /Zi")
				
		SET(CMAKE_C_FLAGS_DEBUG "/D_DEBUG /MDd /Zi /Ob0 /Od /RTC1 /MP /sdl-" CACHE STRING "MSVC C Debug MT flags " FORCE)
		SET(CMAKE_CXX_FLAGS_DEBUG "/D_DEBUG /MDd /Zi /Ob0 /Od /RTC1 /MP /sdl-" CACHE STRING "MSVC CXX Debug MT flags " FORCE)
		add_definitions(-DRGE_WIN)
	ENDIF()
	
	if (UNIX)
		SET(CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS} -Ofast -DNDEBUG")
		SET(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS} -Ofast -DNDEBUG")
		SET(CMAKE_C_FLAGS_DEBUG "${CMAKE_C_FLAGS} -D_DEBUG")
		SET(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS} -D_DEBUG")
		add_definitions(-DRGE_UNIX)
	ENDIF()
	
	add_executable(${APP_NAME} ${SRC})
	target_link_libraries (${APP_NAME} ${LIBS})
	link_directories()
	add_dependencies(${APP_NAME} RGE)
ENDMACRO(SETUP_APP)

MACRO(ADD_RGE RGE_PATH)

	add_subdirectory(${RGE_PATH} CMakeFiles/RGE)
	
	include_directories(${RGE_PATH})
	
	SET (APP_SYSTEM_INCLUDE ${APP_SYSTEM_INCLUDE} ${RGE_PATH})

ENDMACRO(ADD_RGE)